variable "name" {
  type        = string
  description = "Name of the lambda function"
}

variable "tags" {
  type        = map(string)
  description = "Tags to apply to the resources generated by this module"
  default     = {}

}

variable "environment_vars" {
  type        = map(string)
  description = "Environment variables to apply to the lambda function"
  default     = {}
}

variable "include_aws_param_store_secrets_layer" {
  type        = bool
  description = "Include the AWS Parameter Store Secrets Layer"
  default     = false
}

variable "memory_size" {
  type        = number
  description = "Memory size for the lambda function"
  default     = 128
}

locals {
  tags = merge(var.tags, {
    "Name"   = var.name
    "Source" = "Terraform"
    "Module" = "golang-lambda"
  })
  role_name          = "lambda-${var.name}"
  function_code_path = "${path.module}/sample/sample.zip"
  layers             = var.include_aws_param_store_secrets_layer ? ["arn:aws:lambda:us-east-1:177933569100:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:11"] : []
}
